// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irwreedairelbbekrvyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyd3JlZWRhaXJlbGJiZWtydnlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjkzMjAsImV4cCI6MjA3NDI0NTMyMH0.u3HT0MyvL9oQaOH9KHGo1Eu-RsWvTJYq5m1FiV4IOsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});